// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eugkmlzqznjlkfkdxfbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1Z2ttbHpxem5qbGtma2R4ZmJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NjE2NDYsImV4cCI6MjA2NTEzNzY0Nn0.pKB0mI_btgzbdTKkgiN40CmRcZJyAAW7IHrPl6VHolY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);